version: '3.9'

services:
  backend:
    build:
      context: ./ShoesStore
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./ShoesStore:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./shoes-store
    ports:
      - "3000:3000"
    volumes:
      - ./shoes-store:/app
    stdin_open: true

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shoesstore
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
